routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});
Auth::routes(['register' => false]);

Route::middleware('auth')
    ->group(function () {
        Route::get('home', function () { return redirect('home/dashboard');});

        Route::group(['prefix' => 'home'], function () {
            Route::get('dashboard', 'Master\Home\IndexController@dashboard')->name('home');
            Route::resource('password-manager', 'Master\Home\PasswordManagerController');
        });


        Route::group(['prefix' => 'dashboard'], function () {
            Route::get('/items/{id}', 'Master\Dashboard\ItemsByTypeController@items')->name('dashboard.items');
            Route::get('/printers', 'Master\Dashboard\ItemsByTypeController@printers')->name('dashboard.printers');
        });
        Route::get('/items/search', 'Master\Items\SearchController@tag_id')->name('search.tagid');
        
        Route::get('/log', 'Master\LogController@index')->name('log.index');
        Route::get('/log/create', 'Master\LogController@create')->name('log.create');
        Route::post('/log', 'Master\LogController@store')->name('log.store');
        Route::get('/log/{log}', 'Master\LogController@show')->name('log.show');
        Route::get('/log/{log}/edit', 'Master\LogController@edit')->name('log.edit');
        Route::patch('/log/{log}', 'Master\LogController@update')->name('log.update');

        Route::get('/items/location/{id}', 'Master\Items\LocationController@show')->name('items.location.show');
        Route::get('/items/location', 'Master\Items\LocationController@index')->name('items.location');
        Route::get('/items/log', 'Master\Items\LogController@index')->name('items.log');

    // Limited Access --------------------------------------------------------------------------------------------------
    Route::group(['middleware' => ['privilege']], function () {

        Route::namespace('Master')->group(function () {

            // Controllers Within The "App\Http\Controllers\Master" Namespace
            Route::get('/dashboard', 'Dashboard\IndexController@index')->name('dashboard.index');
            Route::resource('/ips', 'Items\IpsController');

            //Items
            Route::group(['prefix' => 'items'], function () {
                Route::group(['prefix' => 'reports'], function () {
                    Route::get('/', 'Items\Reports\IndexController@index')->name('items.reports.index');
                    Route::get('purchase-date-range', 'Items\Reports\DateRangeController@purchase_date_range')->name('items.reports.index');
                });
            });

            Route::resource('/items', 'Items\IndexController');
            Route::group(['prefix' => 'item'], function () {
                Route::resource('user', 'Items\UserController', ['except' =>['index', 'show']]);
                Route::resource('document', 'Items\DocumentController', ['only' =>['create', 'store', 'destroy']]);
                Route::resource('documents/list', 'Items\DocumentListController', ['only' =>['edit', 'update']]);
                Route::resource('account', 'Items\AccountController', ['names' => 'items-account']);
                Route::resource('log', 'Items\LogController',[
                    'names' => [
                        'create' => 'item_log.create',
                        'store' => 'item_log.store',
                        'show' => 'item_log.show',
                        'edit' => 'item_log.edit',
                        'update' => 'item_log.update',
                        'destroy' => 'item_log.destroy'
                    ], 'except' => ['index']
                ]);
                Route::resource('disposal-date', 'Items\DisposalDateController', ['only' =>['edit', 'update', 'destroy']]);
                Route::resource('computer-name', 'Items\ComputerNameController')
                    ->only(['store', 'destroy'])
                    ->names(['store' => 'computer_name.store', 'destroy' => 'computer_name.destroy']);
            });

            //Documents
            Route::resource('documents/invoices', 'Documents\InvoiceController');
            Route::resource('documents', 'Documents\IndexController');
            //Accounts
            Route::resource('/accounts', 'WebAccounts\IndexController');
            Route::group(['prefix' => 'accounts'], function () {
                Route::resource('user', 'WebAccounts\UsersController', ['except' =>['index']]);
                Route::resource('categories', 'WebAccounts\CategoriesController', ['only' =>['edit', 'update', 'destroy']]);
            });

            // Server Room Maintenance
            Route::resource('room/code', 'RoomMaintenance\LocationController', ['only' =>['show']]);
            Route::resource('room/maintenance', 'RoomMaintenance\IndexController');

            // End Master Namespace ------
        });

        // End Limited Access middleware -
    });

    // Admin -----------------------------------------------------------------------------------------------------------
    Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
        Route::get('/', 'Admin\IndexController@index')->name('admin');
        Route::resource('/brands', 'Admin\BrandsController');
        Route::resource('/types', 'Admin\TypesController');
        Route::resource('/models', 'Admin\ImodelsController');
        Route::resource('/locations', 'Admin\LocationController');
        Route::resource('/sublocations', 'Admin\SublocationController');

        Route::resource('/web-account-types', 'Admin\WebAccountTypesController');
        Route::resource('/groups', 'Admin\GroupsController');
        Route::resource('/icons', 'Admin\IconsController');
        Route::resource('/categories', 'Admin\CategoriesController');

        Route::resource('/users', 'Admin\User\IndexController');
        Route::resource('/users/privileges', 'Admin\User\PrivilegesController', ['only' =>['edit', 'update', 'destroy']]);
    });
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $fillable = [
        'user_id', 'doctype_id', 'title', 'description', 'filename', 'size'
    ];

    public function type()
    {
        return $this->belongsTo('App\Doctype', 'doctype_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function items()
    {
        return $this->belongsToMany('App\Item', 'item_documents', 'document_id', 'item_id')->withPivot('id');
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getFileSizeAttribute()
    {
        $kb = $this->size / 1024;
        return round($kb, 2).' KB';
    }

    public function getDateAttribute()
    {
        return date('m/d/Y', strtotime($this->created_at));
    }

    public function getYearAttribute()
    {
        return date('Y', strtotime($this->created_at));
    }

    public function getTitleTypeAttribute()
    {
        return $this->type->name.' - '.$this->title;
    }
}

app/Http/Controllers/Master/Dashboard/IndexController.php
<?php

namespace App\Http\Controllers\Master\Dashboard;

use App\Doctype;
use App\Item;
use App\ItemLog;
use App\Location;
use App\Sublocation;
use App\Type;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    protected $template;

    public function __construct()
    {
        $this->template = "master.dashboard";
    }

    public function index()
    {
        $i = 1;
        $allInOns = Type::find(1)->total;
        $monitors = Type::find(2)->total;
        $pcTowers = Type::find(4)->total;
        $batteries = Type::find(7)->total;
        $laptops = Type::find(9)->total;
        $receiptPrinters = Type::find(8)->total;
        $tablets = Type::find(20)->total;
        $timeClocks = Type::find(12)->total;
        $webCams = Type::find(6)->total;
        $labelMakers = Type::find(3)->total;
        $pointOfSales = Type::find(21)->total;
        $tvs = Type::find(26)->total;


        $laserPrinters = Type::find(18)->total;
        $mfpPrinters = Type::find(15)->total;
        $inkJetPrinters = Type::find(22)->total;
        $printers = $mfpPrinters + $laserPrinters + $inkJetPrinters;

        $totalItems = Item::all()->count();
        $locations = Location::find([1,2,3,4,5]);
        //Network-Communication Rooms
        $subLocations = Sublocation::networkRooms();

        $itemsLogs = ItemLog::orderBy('updated_at', 'desc')->limit(6)->get();

        $itReports = Doctype::findOrFail(9)->documents()->limit(5)->get();
        $invoices = Doctype::findOrFail(1)->documents()->limit(5)->get();
        $orders = Doctype::findOrFail(2)->documents()->limit(5)->get();
        $ii = 1;
        return view("$this->template.index", compact(
            'batteries',
            'monitors',
            'allInOns',
            'pcTowers',
            'laptops',
            'printers',
            'receiptPrinters',
            'tablets',
            'timeClocks',
            'webCams',
            'labelMakers',
            'pointOfSales',
            'tvs',
            'locations',
            'subLocations',
            'totalItems',
            'itemsLogs',
            'i', 'ii',
            'itReports', 'invoices', 'orders'
        ));
    }
}

app/Http/Controllers/Master/Dashboard/ItemsByTypeController.php
<?php

namespace App\Http\Controllers\Master\Dashboard;

use App\Type;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;

class ItemsByTypeController extends IndexController
{
    protected $view_template;

    public function __construct()
    {
        parent::__construct();
        $this->view_template = "$this->template.printers";
    }

    public function index()
    {
        $laserPrinters = Type::find(18)->items;
        $mfpPrinters = Type::find(15)->items;
        $inkPrinters = Type::find(22)->items;

        $printers = array_merge($laserPrinters, $mfpPrinters, $inkPrinters);//dd($laserPrinters->items);
        $i = 1;

        return view("$this->view_template.index", compact('printers', 'i'));
    }

    public function printers()
    {
        $laserPrinters = Type::find(18)->items;
        $mfpPrinters = Type::find(15)->items;
        $inkPrinters = Type::find(22)->items;

        $items = array_merge($laserPrinters, $mfpPrinters, $inkPrinters);//dd($laserPrinters->items);
        $i = 1;

        return view('master.dashboard.items-by-type', compact('items', 'i'));
    }

    public function items($id)
    {
        $items = Arr::sort(Type::find($id)->items);
        $i = 1;
        return view('master.dashboard.items-by-type', compact('items', 'i'));
    }
}

app/Http/Controllers/Master/Documents/IndexController.php
<?php

namespace App\Http\Controllers\Master\Documents;

use App\Doctype;
use App\Document;
use App\TaxCode;
use App\Http\Resources\Document as DocumentResource;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;

class IndexController extends Controller
{
    protected $template;

    public function __construct()
    {
        $this->template = "master.documents";
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Get list of all documents
        $documents = Document::orderBy('id')->paginate();

        $i = $documents->firstItem();

        session()->put('pageId', $documents->currentPage());

        return view("$this->template.index", compact('documents', 'i'));


        //Return collection of Documents
        //return DocumentResource::collection($documents);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $doctypes = Doctype::all()->pluck('name', 'id');
        $pageId = session()->get('pageId');
        return view("$this->template.create", compact('pageId', 'doctypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'doctype_id' => 'required',
            'title' => 'required',
            'input_file' => 'required'
        ]);

        // all incoming inputs
        $inputs = $request->all();

        $year = date('Y');
        // upload path
        $destinationPath = "public/documents/$year";

        // getting file extension
        $extension = $request->file('input_file')->getClientOriginalExtension();

        // getting file size
        $size = $request->file('input_file')->getSize();

        // Make filename
        $fileName = Str::slug($inputs['title'].'-'.rand(999, 9999), '-').'.'.$extension;

        // uploading file to given path
        $request->file('input_file')->storeAs($destinationPath, $fileName);

        $inputs['filename'] = $fileName;
        $inputs['user_id'] = request()->user()->id;
        $inputs['size'] = $size;

        Document::create($inputs);

        return redirect("/documents");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $document = Document::findOrFail($id);

        //return response()->file("storage/documents/2018/$document->filename");

        return view();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $document = Document::findOrFail($id);
        $doctypes = Doctype::all()->pluck('name', 'id');
        $pageId = session()->get('pageId');
        return view("$this->template.edit", compact('document', 'doctypes', 'pageId'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $document = Document::findOrFail($id);
        $document->update($request->all());
        return redirect("documents/$id");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
    * Upload Document to the server
    * @param object $file
    * @param string $title
    * @return $array
    */
    public static function upload($file, $title)
    {
        $year = date('Y');
        // upload path
        $destinationPath = "public/documents/$year";
        // getting file extension
        $extension = $file->getClientOriginalExtension();
        // getting file size
        $size = $file->getSize();
        // Make filename
        $fileName = Str::slug($title.'-'.rand(999, 9999), '-').'.'.$extension;
        // uploading file to given path
        $file->storeAs($destinationPath, $fileName);

        return ['size' => $size, 'filename' => $fileName];
    }
}

app/Http/Controllers/Master/Home/IndexController.php
<?php

namespace App\Http\Controllers\Master\Home;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    protected $template;

    public function __construct()
    {
        //$this->middleware('auth');
        $this->template = "master.home";
    }

    public function dashboard()
    {
        return view("$this->template.dashboard");
    }
}

app/Http/Controllers/Master/Items/ComputerNameController.php
<?php

namespace App\Http\Controllers\Master\Items;

use App\ComputerName;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ComputerNameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'operating_system_id' => 'required',
            'name' => 'required'
        ]);
        ComputerName::create($request->all());
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $name = ComputerName::findOrFail($id);
        $name->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Master/Items/Reports/IndexController.php
<?php

namespace App\Http\Controllers\Master\Items\Reports;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index()
    {
        $pageId = session()->get('pageId');
        return view('master.items.reports.index', compact('pageId'));
    }


}

resources/views/master/documents/create.blade.php
@extends('layouts.master')

@section('title', 'Add Document')

@section('hTitle', 'Upload new Document file')
    
@section('content')
    <div class="box">
        <!-- /.box-header -->
        {!! Form::open(['url' => 'documents', 'files' => true, 'id' => 'myForm']) !!}
        <div class="box-body">
            @include('master.documents.formBody')
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3">
                    <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                        {!! Form::label('input_file', 'File') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
                        {!! Form::file('input_file',['class' => 'form-control', 'id' => 'inputFile']); !!}
                        <p class="help-block">Acceptable file types: PDF, DOC, DOCX, TXT</p>
                        @if ($errors->has('input_file'))
                            <span class="help-block"><strong>{{ $errors->first('input_file') }}</strong></span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            @include('parts.saveCancelBtns', ['cancel' => "documents?page=$pageId"])
        </div>
        {!! Form::close() !!}
        <!-- /.box-body -->
    </div>
@endsection


@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#myForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/master/documents/edit.blade.php
@extends('layouts.master')

@section('title', $document->title)

@section('hTitle')
    Edit {{ $document->title }}
@endsection

@section('content')
    <div class="box">
        <!-- /.box-header -->
        {!! Form::model($document, ['method' => 'PATCH', 'action' => ['Master\DocumentsController@update', $document->id], 'id' => 'myForm']) !!}
        <div class="box-body">
            @include('master.documents.formBody')
        </div>
        <div class="box-footer">
            @include('parts.saveCancelBtns', ['cancel' => "documents?page=$pageId"])
        </div>
    {!! Form::close() !!}
    <!-- /.box-body -->
    </div>
@endsection


@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#myForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/master/documents/formBody.blade.php
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="form-group{{ $errors->has('doctype_id') ? ' has-error' : '' }}">
            {!! Form::label('doctype_id', 'Type') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
            {!! Form::select('doctype_id', $doctypes, null, ['class' => 'form-control', 'placeholder' => 'select type', 'autofocus']) !!}
            @if ($errors->has('doctype_id'))
                <span class="help-block"><strong>{{ $errors->first('doctype_id') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
            {!! Form::label('title', 'Title') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
            <div class="input-group">
                <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="Serial Number"><i class="fa fa-hashtag fa-fw" aria-hidden="true"></i></span>
                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'document title', 'autocomplete' => 'off']) !!}
            </div>
            @if ($errors->has('title'))
                <span class="help-block"><strong>{{ $errors->first('title') }}</strong></span>
            @endif
        </div>
        <!-- Textarea with ckeditor -->
        @include('parts.textarea', ['name' => 'description', 'title' => 'Description'])
    </div>
</div>

resources/views/master/documents/index.blade.php
@extends('layouts.master')

@section('title', 'Documents')

@section('hTitle', 'Documents')
    
@section('breadcrumbs'){{ Breadcrumbs::render('documents') }}@endsection

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">
                Documents Total <span class="badge">{{ $documents->total() }}</span>
                <a class="btn btn-primary btn-xs aBtn" data-toggle="tooltip" data-placement="top" title="Add new document" href="{{ url('documents/create') }}"><i class="fa fa-fw fa-plus"></i> Add</a>
            </h3>
            <div class="box-tools">
                {{ $documents->links('vendor.pagination.admin-lte') }}
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body no-padding">
            @include('parts.session-message')
            <div class="table-responsive">
                <table class="table table-condensed table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Type</th>
                        <th>Title</th>
                        <th>Uploaded by</th>
                        <th>File Size</th>
                        <th>Date</th>
                        <th colspan="2"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($documents as $document)
                        <tr>
                            <th scope="row">{{ $i++ }}</th>
                            <td>{{ $document->type->name }}</td>
                            <td>{{ $document->title }}</td>
                            <td>{{ $document->user->name }}</td>
                            <td>{{ $document->file_size }}</td>
                            <td>{{ $document->date }}</td>
                            <td>
                                <a class="btn btn-default btn-xs" download="{{ $document->filename }}" href="{{ asset("storage/documents/$document->year/$document->filename") }}" data-toggle="tooltip" data-placement="top" title="download the file"><i class="fa fa-fw fa-download"></i></a>
                                <a class="btn btn-default btn-xs" href="{{ asset("storage/documents/$document->year/$document->filename") }}" target="_blank" data-toggle="tooltip" data-placement="top" title="view in browser"><i class="fa fa-fw fa-eye"></i></a>
                            </td>
                            <td><a class="btn btn-primary btn-xs aBtn" href="{{ url("/documents/$document->id/edit") }}"><i class="fa fa-fw fa-pencil"></i></a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {{ $documents->links('vendor.pagination.admin-lte') }}
        </div>
    </div>
@endsection