routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});
Auth::routes(['register' => false]);

Route::middleware('auth')
    ->group(function () {
        Route::get('home', function () { return redirect('home/dashboard');});

        Route::group(['prefix' => 'home'], function () {
            Route::get('dashboard', 'Master\Home\IndexController@dashboard')->name('home');
            Route::resource('password-manager', 'Master\Home\PasswordManagerController');
        });


        Route::group(['prefix' => 'dashboard'], function () {
            Route::get('/items/{id}', 'Master\Dashboard\ItemsByTypeController@items')->name('dashboard.items');
            Route::get('/printers', 'Master\Dashboard\ItemsByTypeController@printers')->name('dashboard.printers');
        });
        Route::get('/items/search', 'Master\Items\SearchController@tag_id')->name('search.tagid');
        
        Route::get('/log', 'Master\LogController@index')->name('log.index');
        Route::get('/log/create', 'Master\LogController@create')->name('log.create');
        Route::post('/log', 'Master\LogController@store')->name('log.store');
        Route::get('/log/{log}', 'Master\LogController@show')->name('log.show');
        Route::get('/log/{log}/edit', 'Master\LogController@edit')->name('log.edit');
        Route::patch('/log/{log}', 'Master\LogController@update')->name('log.update');

        Route::get('/items/location/{id}', 'Master\Items\LocationController@show')->name('items.location.show');
        Route::get('/items/location', 'Master\Items\LocationController@index')->name('items.location');
        Route::get('/items/log', 'Master\Items\LogController@index')->name('items.log');

    // Limited Access --------------------------------------------------------------------------------------------------
    Route::group(['middleware' => ['privilege']], function () {

        Route::namespace('Master')->group(function () {

            // Controllers Within The "App\Http\Controllers\Master" Namespace
            Route::get('/dashboard', 'Dashboard\IndexController@index')->name('dashboard.index');
            Route::resource('/ips', 'Items\IpsController');

            //Items
            Route::group(['prefix' => 'items'], function () {
                Route::group(['prefix' => 'reports'], function () {
                    Route::get('/', 'Items\Reports\IndexController@index')->name('items.reports.index');
                    Route::get('purchase-date-range', 'Items\Reports\DateRangeController@purchase_date_range')->name('items.reports.index');
                });
            });

            Route::resource('/items', 'Items\IndexController');
            Route::group(['prefix' => 'item'], function () {
                Route::resource('user', 'Items\UserController', ['except' =>['index', 'show']]);
                Route::resource('document', 'Items\DocumentController', ['only' =>['create', 'store', 'destroy']]);
                Route::resource('documents/list', 'Items\DocumentListController', ['only' =>['edit', 'update']]);
                Route::resource('account', 'Items\AccountController', ['names' => 'items-account']);
                Route::resource('log', 'Items\LogController',[
                    'names' => [
                        'create' => 'item_log.create',
                        'store' => 'item_log.store',
                        'show' => 'item_log.show',
                        'edit' => 'item_log.edit',
                        'update' => 'item_log.update',
                        'destroy' => 'item_log.destroy'
                    ], 'except' => ['index']
                ]);
                Route::resource('disposal-date', 'Items\DisposalDateController', ['only' =>['edit', 'update', 'destroy']]);
                Route::resource('computer-name', 'Items\ComputerNameController')
                    ->only(['store', 'destroy'])
                    ->names(['store' => 'computer_name.store', 'destroy' => 'computer_name.destroy']);
            });

            //Documents
            Route::resource('documents/invoices', 'Documents\InvoiceController');
            Route::resource('documents', 'Documents\IndexController');
            //Accounts
            Route::resource('/accounts', 'WebAccounts\IndexController');
            Route::group(['prefix' => 'accounts'], function () {
                Route::resource('user', 'WebAccounts\UsersController', ['except' =>['index']]);
                Route::resource('categories', 'WebAccounts\CategoriesController', ['only' =>['edit', 'update', 'destroy']]);
            });

            // Server Room Maintenance
            Route::resource('room/code', 'RoomMaintenance\LocationController', ['only' =>['show']]);
            Route::resource('room/maintenance', 'RoomMaintenance\IndexController');

            // End Master Namespace ------
        });

        // End Limited Access middleware -
    });

    // Admin -----------------------------------------------------------------------------------------------------------
    Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
        Route::get('/', 'Admin\IndexController@index')->name('admin');
        Route::resource('/brands', 'Admin\BrandsController');
        Route::resource('/types', 'Admin\TypesController');
        Route::resource('/models', 'Admin\ImodelsController');
        Route::resource('/locations', 'Admin\LocationController');
        Route::resource('/sublocations', 'Admin\SublocationController');

        Route::resource('/web-account-types', 'Admin\WebAccountTypesController');
        Route::resource('/groups', 'Admin\GroupsController');
        Route::resource('/icons', 'Admin\IconsController');
        Route::resource('/categories', 'Admin\CategoriesController');

        Route::resource('/users', 'Admin\User\IndexController');
        Route::resource('/users/privileges', 'Admin\User\PrivilegesController', ['only' =>['edit', 'update', 'destroy']]);
    });
});

app/Sublocation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sublocation extends Model
{
    use SoftDeletes;

    public $timestamps = false;
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $fillable = [
        'location_id', 'room_code', 'sublocation_name_id'
    ];

    // Database Relationships ------------------------------------------------------------------------------------------
    public function location()
    {
        return $this->belongsTo('App\Location', 'location_id');
    }

    public function items()
    {
        return $this->hasMany('App\Item', 'sublocation_id');
    }

    public function name()
    {
        return $this->hasOne('App\SublocationName', 'id', 'sublocation_name_id');

    }

    public function roomMaintenance()
    {
        return $this->hasMany('App\RoomMaintenance', 'sublocation_id');
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getLocationNameAttribute()
    {
        if($this->sublocation_name_id)
            $name = $this->name->name." [$this->room_code]";
        else
            $name = $this->room_code;

        return $this->location->name.' → '.$name;
    }

    public function getTotalItemsPerRoomAttribute()
    {
        return $this->items->count();
    }

    public function getRoomNameAttribute()
    {
        if($this->sublocation_name_id)
            $name = $this->name->name;
        else
            $name = 'N/A';

        return $name;
    }

    public function getRoomCodeSlugAttribute()
    {
        return strtolower($this->room_code);
    }

    /**
     * Return All Network Rooms
     * @return mixed
     */
    public static function networkRooms()
    {
        return Sublocation::find([10,31,40,50,67,64,68]);
    }
}

app/Http/Controllers/Admin/SublocationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Location;
use App\Sublocation;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class SublocationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sublocations = Sublocation::whereNull('deleted_at')->paginate();
        session()->put('pageId', $sublocations->currentPage());
        $i = $sublocations->firstItem();
        return view('admin.sublocation.index', compact('sublocations', 'i'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $locations = Location::orderBy('name')
            ->whereNull('deleted_at')
            ->pluck('name', 'id');

        return view('admin.sublocation.create', compact('locations'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Requests\SublocationRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Requests\SublocationRequest $request)
    {
        $sublocation = Sublocation::create($request->all());
        return redirect("admin/sublocations/$sublocation->id")->with('message-success', 'New Sublocation has been created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sublocation = Sublocation::findOrFail($id);
        $pageId = session()->get('pageId');
        return view('admin.sublocation.show', compact('sublocation', 'pageId'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sublocation = Sublocation::findOrFail($id);
        $locations = Location::orderBy('name')
            ->whereNull('deleted_at')
            ->pluck('name', 'id');

        return view('admin.sublocation.edit', compact('locations', 'sublocation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Requests\SublocationRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Requests\SublocationRequest $request, $id)
    {
        $sublocation = Sublocation::findOrFail($id);
            $sublocation->update($request->all());

        return redirect("admin/sublocations/$id")->with('message-success', 'Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sublocation = Sublocation::findOrFail($id);
        $sublocation->delete();
        $pageId = session()->get('pageId');

        return redirect("admin/sublocations?page=$pageId")->with('message-success', 'Sublocation has been deleted successfully.');
    }
}

resources/views/admin/sublocation/create.blade.php
@extends('layouts.admin')

@section('title', 'Sublocation')

@section('hTitle')
    Add New Sublocation
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Add New Sublocation</h3>
                </div>
                <!-- /.box-header -->
                {!! Form::open(['url' => 'admin/sublocations', 'id' => 'myForm']) !!}
                <div class="box-body">
                    @include('admin.sublocation.formBody')
                </div>
                <div class="box-footer">
                    @include('parts.saveCancelBtns', ['cancel' => 'admin/sublocations'])
                </div>
            {!! Form::close() !!}
            <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#myForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).html('<i class="fa fa-spinner fa-pulse fa-fw"></i> processing...');
            });
        });
    </script>
@endsection

resources/views/admin/sublocation/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Sublocation')

@section('hTitle')
    Edit Sublocation
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Edit Sublocation</h3>
                </div>
                <!-- /.box-header -->
                {!! Form::model($sublocation, ['method' => 'PATCH', 'action' => ['Admin\SublocationController@update', $sublocation->id], 'id' => 'myForm']) !!}
                <div class="box-body">
                    @include('admin.sublocation.formBody')
                </div>
                <div class="box-footer">
                    @include('parts.saveCancelBtns', ['cancel' => "admin/sublocations/$sublocation->id"])
                </div>
            {!! Form::close() !!}
            <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#myForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).html('<i class="fa fa-spinner fa-pulse fa-fw"></i> processing...');
            });
        });
    </script>
@endsection

resources/views/admin/sublocation/formBody.blade.php
<div class="row">
    <div class="col-lg-6">
        <div class="form-group{{ $errors->has('location_id') ? ' has-error' : '' }}">
            {!! Form::label('location_id', 'Main Location') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
            {!! Form::select('location_id', $locations, null, ['class' => 'form-control', 'placeholder' => 'select main location', 'autofocus']) !!}
            @if ($errors->has('location_id'))
                <span class="help-block"><strong>{{ $errors->first('location_id') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('room_code') ? ' has-error' : '' }}">
            {!! Form::label('room_code', 'Room Code') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
            <div class="input-group">
                <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="address"><i class="fa fa-tag fa-fw" aria-hidden="true"></i></span>
                {!! Form::text('room_code', null, ['class' => 'form-control', 'placeholder' => 'room code', 'autocomplete' => 'off']) !!}
            </div>
            @if ($errors->has('room_code'))
                <span class="help-block"><strong>{{ $errors->first('room_code') }}</strong></span>
            @endif
        </div>
        <!-- Textarea with ckeditor -->
        @include('parts.textarea', ['name' => 'description', 'title' => 'Description'])
    </div>
</div>

resources/views/admin/sublocation/index.blade.php
@extends('layouts.admin')

@section('title', 'Sublocations')

@section('hTitle')
    Sublocations
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Sublocations List <a class="btn btn-primary btn-xs aBtn" href="{{ url('admin/sublocations/create') }}"><i class="fa fa-fw fa-plus"></i> Add</a></h3>

                    <div class="box-tools">
                        {{ $sublocations->links('vendor.pagination.admin-lte') }}
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">
                    @include('parts.session-message')
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Main</th>
                            <th>Sublocation Name</th>
                            <th class="text-center">Sublocation Code</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($sublocations as $sublocation)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $sublocation->location->name }}</td>
                                <td>{{ $sublocation->room_name }}</td>
                                <td class="text-center">{{ $sublocation->room_code }}</td>
                                <td>
                                    <a class="btn btn-default btn-xs aBtn" href="{{ url("admin/sublocations/$sublocation->id") }}"><i class="fa fa-fw fa-eye"></i></a>
                                    <a class="btn btn-primary btn-xs aBtn" href="{{ url("admin/sublocations/$sublocation->id/edit") }}"><i class="fa fa-fw fa-pencil"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    {{ $sublocations->links('vendor.pagination.admin-lte') }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sublocation/show.blade.php
@extends('layouts.admin')

@section('title', "$sublocation->location_name")

@section('hTitle')
    @include('parts.backBtn', ['url' => "admin/sublocations?page=$pageId", 'title' => 'back to sublocation list'])
    {{ $sublocation->location_name }}
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">{{ $sublocation->location_name }} </h3>
                    <a href="{{ url("admin/sublocations/$sublocation->id/edit") }}" class="btn btn-primary pull-right aBtn"><i class="fa fa-fw fa-pencil" aria-hidden="true"></i> Edit</a>
                </div><!-- /.box-header -->

                <div class="box-body">
                    @include('parts.session-message')
                    <div class="row">
                        <div class="col-lg-6">
                            <ul>
                                <li>{{ $sublocation->location->name }}</li>
                                <li>{{ $sublocation->room_code }}</li>
                                <li></li>
                            </ul>
                        </div>
                        <div class="col-lg-6">

                        </div>
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    @include('parts.trashBtn', ['action' => ['Admin\SublocationController@destroy', $sublocation->id], 'btnTitle' => $sublocation->name])
                </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('[data-toggle=confirmation]').confirmation({
                rootSelector: '[data-toggle=confirmation]',
                // other options
            });

            $(".deleteBtnForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).html('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection