routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});
Auth::routes(['register' => false]);

Route::middleware('auth')
    ->group(function () {
        Route::get('home', function () { return redirect('home/dashboard');});

        Route::group(['prefix' => 'home'], function () {
            Route::get('dashboard', 'Master\Home\IndexController@dashboard')->name('home');
            Route::resource('password-manager', 'Master\Home\PasswordManagerController');
        });


        Route::group(['prefix' => 'dashboard'], function () {
            Route::get('/items/{id}', 'Master\Dashboard\ItemsByTypeController@items')->name('dashboard.items');
            Route::get('/printers', 'Master\Dashboard\ItemsByTypeController@printers')->name('dashboard.printers');
        });
        Route::get('/items/search', 'Master\Items\SearchController@tag_id')->name('search.tagid');
        
        Route::get('/log', 'Master\LogController@index')->name('log.index');
        Route::get('/log/create', 'Master\LogController@create')->name('log.create');
        Route::post('/log', 'Master\LogController@store')->name('log.store');
        Route::get('/log/{log}', 'Master\LogController@show')->name('log.show');
        Route::get('/log/{log}/edit', 'Master\LogController@edit')->name('log.edit');
        Route::patch('/log/{log}', 'Master\LogController@update')->name('log.update');

        Route::get('/items/location/{id}', 'Master\Items\LocationController@show')->name('items.location.show');
        Route::get('/items/location', 'Master\Items\LocationController@index')->name('items.location');
        Route::get('/items/log', 'Master\Items\LogController@index')->name('items.log');

    // Limited Access --------------------------------------------------------------------------------------------------
    Route::group(['middleware' => ['privilege']], function () {

        Route::namespace('Master')->group(function () {

            // Controllers Within The "App\Http\Controllers\Master" Namespace
            Route::get('/dashboard', 'Dashboard\IndexController@index')->name('dashboard.index');
            Route::resource('/ips', 'Items\IpsController');

            //Items
            Route::group(['prefix' => 'items'], function () {
                Route::group(['prefix' => 'reports'], function () {
                    Route::get('/', 'Items\Reports\IndexController@index')->name('items.reports.index');
                    Route::get('purchase-date-range', 'Items\Reports\DateRangeController@purchase_date_range')->name('items.reports.index');
                });
            });

            Route::resource('/items', 'Items\IndexController');
            Route::group(['prefix' => 'item'], function () {
                Route::resource('user', 'Items\UserController', ['except' =>['index', 'show']]);
                Route::resource('document', 'Items\DocumentController', ['only' =>['create', 'store', 'destroy']]);
                Route::resource('documents/list', 'Items\DocumentListController', ['only' =>['edit', 'update']]);
                Route::resource('account', 'Items\AccountController', ['names' => 'items-account']);
                Route::resource('log', 'Items\LogController',[
                    'names' => [
                        'create' => 'item_log.create',
                        'store' => 'item_log.store',
                        'show' => 'item_log.show',
                        'edit' => 'item_log.edit',
                        'update' => 'item_log.update',
                        'destroy' => 'item_log.destroy'
                    ], 'except' => ['index']
                ]);
                Route::resource('disposal-date', 'Items\DisposalDateController', ['only' =>['edit', 'update', 'destroy']]);
                Route::resource('computer-name', 'Items\ComputerNameController')
                    ->only(['store', 'destroy'])
                    ->names(['store' => 'computer_name.store', 'destroy' => 'computer_name.destroy']);
            });

            //Documents
            Route::resource('documents/invoices', 'Documents\InvoiceController');
            Route::resource('documents', 'Documents\IndexController');
            //Accounts
            Route::resource('/accounts', 'WebAccounts\IndexController');
            Route::group(['prefix' => 'accounts'], function () {
                Route::resource('user', 'WebAccounts\UsersController', ['except' =>['index']]);
                Route::resource('categories', 'WebAccounts\CategoriesController', ['only' =>['edit', 'update', 'destroy']]);
            });

            // Server Room Maintenance
            Route::resource('room/code', 'RoomMaintenance\LocationController', ['only' =>['show']]);
            Route::resource('room/maintenance', 'RoomMaintenance\IndexController');

            // End Master Namespace ------
        });

        // End Limited Access middleware -
    });

    // Admin -----------------------------------------------------------------------------------------------------------
    Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
        Route::get('/', 'Admin\IndexController@index')->name('admin');
        Route::resource('/brands', 'Admin\BrandsController');
        Route::resource('/types', 'Admin\TypesController');
        Route::resource('/models', 'Admin\ImodelsController');
        Route::resource('/locations', 'Admin\LocationController');
        Route::resource('/sublocations', 'Admin\SublocationController');

        Route::resource('/web-account-types', 'Admin\WebAccountTypesController');
        Route::resource('/groups', 'Admin\GroupsController');
        Route::resource('/icons', 'Admin\IconsController');
        Route::resource('/categories', 'Admin\CategoriesController');

        Route::resource('/users', 'Admin\User\IndexController');
        Route::resource('/users/privileges', 'Admin\User\PrivilegesController', ['only' =>['edit', 'update', 'destroy']]);
    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    public $timestamps = false;

    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $fillable = [
        'group_id', 'parent_id', 'name', 'description', 'picture_id', 'icon_id'
    ];

    public function group()
    {
        return $this->belongsTo('App\Group', 'group_id');
    }

    // ACCESSORS -------------------------------------------------------------------------------------------------------
    public function getGroupCategoryNameAttribute()
    {
        if($this->group)
            return $this->name.' <i class="fa fa-fw fa-angle-double-right" aria-hidden="true"></i> '.$this->group->name;
        else
            return $this->name.' <i class="fa fa-fw fa-angle-double-right" aria-hidden="true"></i> ---';
    }

    public function getHtmlIconAttribute()
    {
        if($this->icon_id)
            return $this->icon->icon;
        else
            return '<i class="fa fa-fw fa-times-circle-o" aria-hidden="true"></i>';
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Group;
use App\Icon;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('name')->paginate();
        $i = $categories->firstItem();
        session()->put('pageId', $categories->currentPage());

        return view('admin.categories.index', compact('categories', 'i'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $icons = Icon::all()->pluck('name_html_icon', 'id');
        $groups = Group::all()->pluck('name', 'id');
        $pageId = session()->get('pageId');
        return view('admin.categories.create', compact('pageId', 'icons', 'groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Requests\CategoriesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\CategoriesRequest $request)
    {
        $category = Category::create($request->all());
        return redirect("/admin/categories/$category->id")->with('message-success', 'The Category has been created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);
        $pageId = session()->get('pageId');
        return view("admin.categories.show", compact('category', 'pageId'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $icons = Icon::all()->pluck('name_html_icon', 'id');
        $groups = Group::all()->pluck('name', 'id');
        $pageId = session()->get('pageId');
        return view("admin.categories.edit", compact('category', 'pageId', 'icons', 'groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Requests\CategoriesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\CategoriesRequest $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Master/WebAccounts/CategoriesController.php
<?php

namespace App\Http\Controllers\Master\WebAccounts;

use App\Category;
use App\WebAccount;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = WebAccount::findOrFail($id);
        $categories = Category::all()->pluck('group_category_name', 'id');
        $pageId = session()->get('pageId');
        $account->category_id =  $account->categories->pluck('name', 'id');
        $i = 1;

        return view('master.web-accounts.categories.edit', compact('account', 'categories', 'pageId', 'i'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'category_id' => 'required'
        ]);
        $account = WebAccount::findOrFail($id);
        $account->categories()->detach();
        $account->categories()->attach($request->category_id);
        return redirect("/accounts/$account->id");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $account = WebAccount::findOrFail($id);
        $account->categories()->detach();
        return redirect("/accounts/$account->id");
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', 'Add category')

@section('hTitle')
    Add New Category
@endsection

@section('breadcrumbs')
    <li><a href="{{ url("/admin/categories?page=$pageId") }}">Categories</a></li>
    <li class="active">Add</li>
@endsection

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Add New Category</h3>
        </div>
        <!-- /.box-header -->
        {!! Form::open(['url' => 'admin/categories', 'id' => 'myForm']) !!}
        <div class="box-body">
            @include('admin.categories.formBody')
        </div>
        <div class="box-footer">
            @include('parts.saveCancelBtns', ['cancel' => "/admin/categories?page=$pageId"])
        </div>
    {!! Form::close() !!}
    <!-- /.box-body -->
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#myForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit category')

@section('hTitle')
    Edit {{ $category->name }} Category
@endsection

@section('breadcrumbs')
    <li><a href="{{ url("/admin/categories?page=$pageId") }}">Categories</a></li>
    <li><a href="{{ url("/admin/categories/$category->id") }}">{{ $category->name }}</a></li>
    <li class="active">Edit</li>
@endsection

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Edit {{ $category->name }} Category</h3>
        </div>
        <!-- /.box-header -->
        {!! Form::model($category, ['method' => 'PATCH', 'action' => ['Admin\CategoriesController@update', $category->id], 'id' => 'myForm']) !!}
        <div class="box-body">
            @include('admin.categories.formBody')
        </div>
        <div class="box-footer">
            @include('parts.saveCancelBtns', ['cancel' => "/admin/categories?page=$pageId"])
        </div>
        {!! Form::close() !!}
        <!-- /.box-body -->
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#myForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/categories/formBody.blade.php
<div class="row">
    <div class="col-lg-6">
        <div class="form-group{{ $errors->has('group_id') ? ' has-error' : '' }}">
            {!! Form::label('group_id', 'Group') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
            {!! Form::select('group_id', $groups, null, ['class' => 'form-control', 'placeholder' => 'select group', 'autofocus']) !!}
            @if ($errors->has('group_id'))
                <span class="help-block"><strong>{{ $errors->first('group_id') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('name', 'Category Name') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="required field"></i>
            <div class="input-group">
                <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="Serial Number"><i class="fa fa-hashtag fa-fw" aria-hidden="true"></i></span>
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'group name', 'autocomplete' => 'off']) !!}
            </div>
            @if ($errors->has('name'))
                <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group{{ $errors->has('icon_id') ? ' has-error' : '' }}">
            <strong>Icons</strong>
            <ul class="list-unstyled">
                @foreach($icons as $id => $name)
                    <li><label>{!! Form::radio("icon_id", $id); !!} {!! $name !!}</label></li>
                @endforeach
            </ul>
            @if ($errors->has('icon_id'))
                <span class="help-block"><strong>{{ $errors->first('icon_id') }}</strong></span>
            @endif
        </div>
    </div>
</div>
<!-- Textarea with ckeditor -->
@include('parts.textarea', ['name' => 'description', 'title' => 'Description'])

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('title', 'Categories')

@section('hTitle')
    Categories
@endsection

@section('breadcrumbs')
    <li class="active">Categories</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Categories list <span class="badge">{{ $categories->total() }}</span></h3>
            <a class="btn btn-primary btn-xs aBtn" data-toggle="tooltip" data-placement="top" title="Add new Group" href="{{ url('/admin/categories/create') }}"><i class="fa fa-fw fa-plus"></i> Add</a>
        </div>
        <!-- /.box-header -->
        <div class="box-body no-padding">
            <div class="table-responsive">
                <table class="table table-hover table-condensed" role="grid">
                    <thead>
                    <tr role="row">
                        <th>#</th>
                        <th>Name</th>
                        <th class="text-center">Icon</th>
                        <th colspan="3"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr role="row">
                            <th scope="row">{{ $i++ }}</th>
                            <td>{{ $category->name }}</td>
                            <td class="text-center">{!! $category->html_icon !!}</td>
                            <td class="text-center"><a class="btn btn-default btn-xs aBtn" href="{{ url("admin/categories/$category->id") }}"><i class="fa fa-fw fa-eye"></i></a></td>
                            <td class="text-center"><a class="btn btn-primary btn-xs aBtn" href="{{ url("admin/categories/$category->id/edit") }}"><i class="fa fa-fw fa-pencil"></i></a></td>
                            <td class="text-center">@include('parts.trashBtnSm', ['action' => ['Admin\CategoriesController@destroy', $category->id], 'btnTitle' => "$category->name Category"])</td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th class="text-center">Icon</th>
                        <th colspan="3"></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            @include('parts.session-message')
            {{ $categories->links('vendor.pagination.admin-lte') }}
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('[data-toggle=confirmation]').confirmation({
                rootSelector: '[data-toggle=confirmation]'
            });

            $(".deleteBtnForm").submit(function() {
                $(this).closest('form').find(':submit').prop('disabled',true).children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.admin')

@section('title', $category->name)

@section('hTitle')
    @include('parts.backBtn', ['url' => "/admin/categories?page=$pageId", 'title' => 'back to the list'])
    {{ $category->name }}
@endsection

@section('breadcrumbs')
    <li><a href="{{ url("/admin/categories?page=$pageId") }}">Categories</a></li>
    <li class="active">{{ $category->name }} Category</li>
@endsection

@section('content')

@endsection